import os
import sys
import time
import openai
from typing import List, Tuple
from utils.dataset import SatDataset, custom_collate
from utils.data_analysis import log_data_sample
from torch.utils.data import DataLoader
from dotmap import DotMap
from tqdm import tqdm
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

os.environ["ROOT_PATH"] = os.getcwd()
sys.path.append(os.environ["ROOT_PATH"])

# openai.api_key = os.getenv("OPENAI_API_KEY")


# openai.organization = ""
# print(openai.Model.list())

def query_gpt(model_name: str, preferences: str) -> Tuple[str, int, int]:
    """
    :param model_name: gpt-4, gpt-3.5
    :param preferences: food preferences of people
    :return: raw output generated by gpt-* model, # prompt_tokens, # completion_tokens
    """
    model = None
    if model_name == 'gpt-4':
        model = 'gpt-4-1106-preview'
    elif model_name == 'gpt-3.5':
        model = 'gpt-3.5-turbo-1106'

    response = openai.ChatCompletion.create(
        model=model,  # gpt-4-1106-preview, gpt-3.5-turbo-1106
        messages=[
            {"role": "system", "content": "Your task is to output two distinct lists of food items, one denoting what "
                                          "can be ordered ('orderable') and the other what cannot ('not_orderable'), "
                                          "to meet the preferences of a group of individuals. Each person must find "
                                          "the selection satisfactory based on their likes and dislikes. The "
                                          "satisfaction criteria are: 1. A person is satisfied if at least one liked "
                                          "item is in 'orderable' list or one disliked item is in 'not_orderable' list. "
                                          "2. No item can appear on both lists. 3. All participants must be satisfied "
                                          "by the combination of the two lists. 4. If no such combination exists that "
                                          "satisfies all, output empty lists for both. You always think step-by-step "
                                          "and show all your work in the explanation. "
                                          "Output your final solution as comma separated list of strings in python code "
                                          "<orderable=[...], not_orderable=[...]>."
             },
            {"role": "user", "content": f"{preferences}"},
        ],
        temperature=1,
        max_tokens=4096,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )

    return (response['choices'][0]['message']['content'],
            response['usage']['prompt_tokens'],
            response['usage']['completion_tokens'])

def query_llama(batch_preferences: List[str]) -> Tuple[List[str], List[int], List[int]]:
    prompt = [(f"<s>[INST] <<SYS>>\n"
              f"Your task is to output two distinct lists of food items, one denoting what can be ordered ('orderable') "
              f"and the other what cannot ('not_orderable'), to meet the preferences of a group of individuals. "
              f"Each person must find the selection satisfactory based on their likes and dislikes. The satisfaction "
              f"criteria are: 1. A person is satisfied if at least one liked item is in 'orderable' list or one disliked"
              f" item is in 'not_orderable' list. 2. No item can appear on both lists. 3. All participants must be "
              f"satisfied by the combination of the two lists. 4. If no such combination exists that satisfies all, "
              f"output empty lists for both. You always think step-by-step and show all your work in the explanation. "
              f"Output your final solution as comma separated list of strings in python code <orderable=[...], "
              f"not_orderable=[...]>."
              f"\n<</SYS>>\n\n"
              f"{preferences} [/INST]") for preferences in batch_preferences]

    tokenizer.pad_token = tokenizer.eos_token
    tokenized_prompts = tokenizer(prompt, padding=True, return_tensors="pt").to(device)
    # num_prompt_tokens = model_inputs.input_ids.shape[-1]
    num_prompt_tokens = \
        torch.sum(tokenized_prompts.attention_mask, dim=-1).cpu().numpy()  # attention ids = 1 and pad ids = 0
    output_ids= model.generate(**tokenized_prompts, max_new_tokens=2000)
    gen_output_ids = output_ids[:, tokenized_prompts.input_ids.shape[-1]:]
    num_completion_tokens = output_ids.shape[-1] - num_prompt_tokens
    generated_out = tokenizer.batch_decode(gen_output_ids, skip_special_tokens=True)
    return generated_out, num_prompt_tokens, num_completion_tokens


if __name__ == "__main__":
    model_name = 'llama-2-70b'  # gpt-4, gpt-3.5, llama-2-70b
    data_path = os.path.join(os.environ["ROOT_PATH"], 'dataset_float_alpha.pkl')
    sat_dataset = SatDataset(root_path=os.environ["ROOT_PATH"], data_path=data_path)

    if model_name == 'llama-2-70b':
        batch_size = 2
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16
        )
        model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-70b-chat-hf",
                                                     device_map="auto",
                                                     quantization_config=bnb_config)
        tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-70b-chat-hf", use_fast=True)
    else:
        batch_size = 1
    sat_loader = DataLoader(sat_dataset, batch_size=batch_size, shuffle=True, collate_fn=custom_collate)

    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

    for data_sample in tqdm(sat_loader):
        data_sample = [DotMap(sample) for sample in data_sample]
        while True:
            try:
                if model_name == 'llama-2-70b':
                    gen_out_list, num_prompt_tokens_list, num_completion_tokens_list = \
                        query_llama([sample.preferences for sample in data_sample])
                    for ind, (gen_out, num_prompt_tokens, num_completion_tokens) \
                            in enumerate(zip(gen_out_list, num_prompt_tokens_list, num_completion_tokens_list)):
                        print(gen_out)
                        print(f'# prompt tokens: {num_prompt_tokens} | # completion tokens: {num_completion_tokens}')
                        log_data_sample(model_name, data_sample[ind].num_vars, data_sample[ind].num_clauses,
                                        data_sample[ind].formula, data_sample[ind].is_sat,
                                        data_sample[ind].preferences, data_sample[ind].menu_items,
                                        gen_out, num_prompt_tokens, num_completion_tokens)
                else:
                    gen_out, num_prompt_tokens, num_completion_tokens = query_gpt(model_name, data_sample.preferences)
                    log_data_sample(model_name, data_sample[0].num_vars, data_sample[0].num_clauses,
                                    data_sample[0].formula, data_sample[0].is_sat,
                                    data_sample[0].preferences, data_sample[0].menu_items,
                                    gen_out, num_prompt_tokens, num_completion_tokens)
                break
            except openai.error.RateLimitError:
                time.sleep(10)
                continue
            except openai.error.APIError:
                time.sleep(10)
                continue
            except openai.error.ServiceUnavailableError:
                time.sleep(10)
                continue
            except openai.error.Timeout:
                time.sleep(10)
                continue
