import os
import sys
from json.decoder import JSONDecodeError
from typing import List, Tuple
import openai
import anthropic
from google import genai

from dotmap import DotMap
from torch.utils.data import DataLoader
from tqdm import tqdm

import system_messages
from utils.data_analysis import log_data_sample, sample_in_context
from utils.dataset import SatDataset, custom_collate

os.environ["ROOT_PATH"] = os.getcwd()
sys.path.append(os.environ["ROOT_PATH"])

openai_api_key = os.environ["OPENAI_API_KEY"]
claude_api_key = os.environ["ANTHROPIC_API_KEY"]
gemini_api_key = os.environ["GEMINI_API_KEY"]
deepseek_api_key = os.environ["DEEPSEEK_API_KEY"]


def query_gpt(
    model_name: str, preferences: str, in_context_examples: str
) -> Tuple[str, int, int]:
    """
    :param model_name: gpt-4, gpt-3.5
    :param preferences: food preferences of people
    :return: raw output generated by gpt-* model, # prompt_tokens, # completion_tokens
    """
    client = None
    llm_model = None

    if model_name == "gpt-4o":
        client = openai.OpenAI(api_key=openai_api_key)
        llm_model = "gpt-4o-2024-11-20"
        max_tokens = 16000
    elif model_name == "claude_37_sonnet":
        client = anthropic.Anthropic()
        llm_model = "claude-3-7-sonnet-20250219"
        max_tokens = 8192
    elif model_name in ["gemini_20", "gemini_25_pro"]:
        client = genai.Client(api_key=gemini_api_key)
        llm_model = (
            "gemini-2.0-flash-exp"
            if model_name == "gemini_20"
            else "gemini-2.5-pro-exp-03-25"
        )
        max_tokens = 8192 if model_name == "gemini_20" else 65000
    elif model_name == "deepseek":
        client = openai.OpenAI(
            api_key=deepseek_api_key, base_url="https://api.deepseek.com"
        )
        llm_model = "deepseek-reasoner"
        max_tokens = 8192

    if client and llm_model:
        response = client.chat.completions.create(
            model=llm_model,
            messages=[
                {
                    "role": "system",
                    "content": system_message + "\n" + in_context_examples,
                },
                {"role": "user", "content": f"Preferences: {preferences}\nSolution: "},
            ],
            temperature=0.3,
            max_tokens=max_tokens,
        )
        if model_name == "deepseek-reasoner":
            content = (
                response.choices[0].message.reasoning_content
                + "```python\n"
                + response.choices[0].message.content
                + "\n```"
            )
            prompt_tokens = response.usage.prompt_tokens
            completion_tokens = response.usage.completion_tokens
        elif model_name == "claude_37_sonnet":
            content = response.content[0].text
            prompt_tokens = response.usage.prompt_tokens
            completion_tokens = response.usage.output_tokens
        elif model_name in ["gemini_20", "gemini_25_pro"]:
            content = response.text
            prompt_tokens = response.usage_metadata.prompt_token_count
            completion_tokens = response.usage_metadata.candidates_token_count
        else:
            content = response.choices[0].message.content
            prompt_tokens = response.usage.prompt_tokens
            completion_tokens = response.usage.completion_tokens
        return (content, prompt_tokens, completion_tokens)

    return "", 0, 0


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--ablation",
        type=str,
        choices=["menu", "sat", "translate"],
        default="menu",
        help="Ablation type. Can be 'menu', 'sat', or 'translate'.",
    )
    # parser.add_argument("--two_sat_flag", action="store_true", help="Flag for 2-SAT.")
    parser.add_argument(
        "--few_shot",
        type=int,
        default=0,
        help="Few-shot learning parameter. Default is 0 for zero-shot.",
    )
    parser.add_argument(
        "--model_name",
        type=str,
        choices=[
            "deepseek_v3",
            "gemini_25_pro",
            "deepseek",
            "gemini_20",
            "gpt-4o",
            "claude_37_sonnet",
        ],
        default="gpt-4o",
        help="Model name to use.",
    )
    parser.add_argument("--job_number", type=str, default="", help="Job number.")
    parser.add_argument(
        "--sat_class",
        type=str,
        default="3sat_float",
        choices=["2sat", "1_3_horn_sat", "1_2_horn_sat", "3sat_float", "3sat_int"],
        help="sat class",
    )
    args = parser.parse_args()

    system_message = system_messages.names[args.ablation]
    data_path = f"data/dataset_{args.sat_class}.pkl"
    sat_dataset = SatDataset(data_path=data_path)

    batch_size = 1
    in_shot_examples = (
        sample_in_context(args.few_shot, "gpt-4o", args.ablation)
        if args.few_shot > 0
        else ""
    )
    sat_loader = DataLoader(
        sat_dataset, batch_size=batch_size, shuffle=True, collate_fn=custom_collate
    )

    print(
        f"Model: {args.model_name} | Ablation: {args.ablation} | Few-shot: {args.few_shot} | SAT class: {args.sat_class}"
    )
    for data_sample in tqdm(sat_loader):
        data_sample = [DotMap(sample) for sample in data_sample]
        while True:
            try:
                data_input = (
                    data_sample[0].preferences
                    if args.ablation in ["menu", "translate"]
                    else data_sample[0].formula
                )
                gen_out, num_prompt_tokens, num_completion_tokens = query_gpt(
                    args.model_name, data_input, in_shot_examples
                )
                log_data_sample(
                    args.model_name,
                    data_sample[0].num_vars,
                    data_sample[0].num_clauses,
                    data_sample[0].formula,
                    data_sample[0].is_sat,
                    data_sample[0].preferences,
                    data_sample[0].menu_items,
                    gen_out,
                    num_prompt_tokens,
                    num_completion_tokens,
                    ablation=args.ablation,
                    job_num=args.job_number,
                    few_shot=args.few_shot,
                    sat_class=args.sat_class,
                )
                break
            except (JSONDecodeError, AttributeError):
                continue
